"""Modify ToDo models to make them more in line with Items Models

Revision ID: 28e77f9d3cbd
Revises: d0401d46058a
Create Date: 2025-10-03 16:21:19.801431

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '28e77f9d3cbd'
down_revision = 'd0401d46058a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
