"""modified todo table

Revision ID: 57471ca9a0f8
Revises: 28e77f9d3cbd
Create Date: 2025-10-14 17:48:59.042120

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '57471ca9a0f8'
down_revision = '28e77f9d3cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
